name: Cleanup Old Shares

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove old shares
        run: |
          current_time=$(date +%s)
          for share_dir in shares/*/; do
            if [ -d "$share_dir" ]; then
              creation_time=$(grep -o 'Shared on [0-9:-]*' "$share_dir/index.html" | cut -d' ' -f3)
              if [ -n "$creation_time" ]; then
                creation_timestamp=$(date -d "$creation_time" +%s)
                age_hours=$(( (current_time - creation_timestamp) / 3600 ))
                if [ $age_hours -gt 24 ]; then
                  rm -rf "$share_dir"
                  echo "Removed old share: $share_dir"
                fi
              else
                echo "No creation time found in $share_dir/index.html, skipping."
              fi
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Remove old shares"
          git push
