name: Cleanup Old Shares

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      
      - name: Remove old shares
        run: |
          # Get current timestamp
          current_time=$(date +%s)
          
          # Loop through share directories
          for share_dir in public/shares/*/; do
            if [ -d "$share_dir" ]; then
              # Get share creation time from index.html
              creation_time=$(grep -o 'Shared on [0-9:-]*' "$share_dir/index.html" | cut -d' ' -f3)
              creation_timestamp=$(date -d "$creation_time" +%s)
              
              # Calculate age in hours
              age_hours=$(( (current_time - creation_timestamp) / 3600 ))
              
              # Remove if older than 24 hours
              if [ $age_hours -gt 24 ]; then
                rm -rf "$share_dir"
                echo "Removed old share: $share_dir"
              fi
            fi
          done
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Remove old shares"
          git push
