name: Create Weather Share

on:
  repository_dispatch:
    types: [create-share]

jobs:
  create-share:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create share directory
        run: |
          mkdir -p public/shares/${{ github.event.client_payload.shareId }}
          touch public/.nojekyll  # Create .nojekyll file
          
      - name: Generate share HTML
        run: |
          cat > public/shares/${{ github.event.client_payload.shareId }}/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Weather Share - ${{ github.event.client_payload.location }}</title>
              <style>
                  body {
                      margin: 0;
                      padding: 0;
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                      background: linear-gradient(135deg, #1e90ff, #00008b);
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                  }
                  .card {
                      background: rgba(255, 255, 255, 0.9);
                      backdrop-filter: blur(10px);
                      border-radius: 24px;
                      padding: 32px;
                      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
                      max-width: 90%;
                      width: 400px;
                      margin: 20px;
                  }
                  .location {
                      font-size: 1.25rem;
                      color: #333;
                      margin-bottom: 24px;
                      display: flex;
                      align-items: center;
                      gap: 8px;
                  }
                  .temperature {
                      font-size: 4rem;
                      font-weight: bold;
                      color: #1e1e1e;
                      margin: 0;
                  }
                  .condition {
                      font-size: 1.5rem;
                      color: #666;
                      margin: 8px 0 24px;
                  }
                  .details {
                      display: grid;
                      grid-template-columns: repeat(3, 1fr);
                      gap: 16px;
                      text-align: center;
                      margin-top: 16px;
                      padding-top: 24px;
                      border-top: 1px solid rgba(0, 0, 0, 0.1);
                  }
                  .detail-item {
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      gap: 8px;
                  }
                  .detail-value {
                      font-size: 1.25rem;
                      font-weight: 600;
                      color: #333;
                  }
                  .detail-label {
                      font-size: 0.875rem;
                      color: #666;
                  }
                  .timestamp {
                      text-align: center;
                      font-size: 0.875rem;
                      color: #666;
                      margin-top: 24px;
                  }
                  .footer {
                      text-align: center;
                      margin-top: 16px;
                      font-size: 0.875rem;
                      color: rgba(255, 255, 255, 0.8);
                  }
              </style>
          </head>
          <body>
              <main>
                  <div class="card">
                      <div class="location">
                          <svg width="20" height="20" viewBox="0 0 24 24" fill="#333">
                              <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/>
                          </svg>
                          ${{ github.event.client_payload.location }}
                      </div>
                      <h1 class="temperature">${{ github.event.client_payload.weather.temp }}°</h1>
                      <div class="condition">${{ github.event.client_payload.weather.condition }}</div>
                      <div class="details">
                          <div class="detail-item">
                              <span class="detail-value">${{ github.event.client_payload.weather.humidity }}%</span>
                              <span class="detail-label">Humidity</span>
                          </div>
                          <div class="detail-item">
                              <span class="detail-value">${{ github.event.client_payload.weather.wind }} km/h</span>
                              <span class="detail-label">Wind</span>
                          </div>
                          <div class="detail-item">
                              <span class="detail-value">${{ github.event.client_payload.weather.feels_like }}°</span>
                              <span class="detail-label">Feels like</span>
                          </div>
                      </div>
                      <div class="timestamp">
                          Shared on ${{ github.event.client_payload.timestamp }}
                      </div>
                  </div>
                  <div class="footer">
                      Shared via Weather App
                  </div>
              </main>
          </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WEATHER_APP_TOKEN }}
          publish_dir: ./public
          keep_files: true

      - name: Schedule cleanup
        run: |
          echo "This share will be automatically removed after 24 hours" 
